name: .NET EC2 Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3

      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

     
      - name: Publish App
        run: dotnet publish -c Release -o publish

    
      - name: Verify Publish Output
        run: ls -R publish


      - name: Copy Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "publish/wwwroot/*"    
          target: "/home/ubuntu/publish"

      
      - name: Deploy to Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Clear old files
            sudo rm -rf /var/www/html/*

            # Move new files into nginx root
            sudo cp -r /home/ubuntu/publish/* /var/www/html/

            # Remove temporary folder
            sudo rm -rf /home/ubuntu/publish

            # Set correct ownership and permissions
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Restart Nginx to serve new files
            sudo systemctl restart nginx